[package]
name = "jafupy/tally"
version = "1.2.0"
description = "A fast, over-optimized line counter for codebases."
license = "GPL-3.0-or-later"
repository = "https://github.com/jafupy/tally"
homepage = "https://jafupy.com/tally/"
entrypoint = "tally"

[[module]]
name = "tally"
source = "target/wasm32-wasmer-wasi/release/tally.wasm"

[[command]]
name = "tally"
module = "tally"
runner = "wasi"
